Added support for even lower bitrate encodes for longer videos

diff --git a/yt-dlp_discord b/yt-dlp_discord
--- a/yt-dlp_discord
+++ b/yt-dlp_discord
@@ -33,7 +33,7 @@ done
 # Thanks to 'tobek' for duration and bitrate calculation examples
 # https://unix.stackexchange.com/a/598360
 
-duration=$(yt-dlp --no-warnings --get-duration ${script_args[@]} | awk -F: '{ print ($1 * 60) + $2 }')
+duration=$(yt-dlp --no-warnings --print duration ${script_args[@]})
 target_size=$(($target_size_mb * 1000 * 1000 * 8)) # target size in bits
 duration_round_up=$((${duration%.*} + 1))
 
@@ -58,11 +58,29 @@ then
    yt_dlp_params=$alt_params
 fi
 
-# If calculated video bitrate is still negative, disable video bitrate calculation
+# If calculated video bitrate is still negative, set video and audio to absolute lowest values
 if [[ ! $video_bitrate -gt 0 ]]
 then
-   audio_bitrate=$((96 * 1000))
-   postprocessor_args_str="VideoConvertor:-bufsize:v $((${target_size} / 20)) -b:a ${audio_bitrate}"
+   audio_bitrate=$((10 * 1000)) # 10kbps audio bitrate
+   video_bitrate=$(($total_bitrate - $audio_bitrate - 10 * 1000)) # 10kbps bitrate overhead
+   # Mono audio, 8kHz (phone audio) sample rate and max res of 144p
+   postprocessor_args_str="VideoConvertor:-b:v ${video_bitrate} -maxrate:v ${video_bitrate} -bufsize:v $((${target_size} / 20)) -vf scale=-2:144 -b:a ${audio_bitrate} -ar 8000 -ac 1"
+fi
+
+# Print debug info if verbose is enabled
+if [[ "$verbose" = "--verbose" ]]
+then
+   echo "Duration (s): $duration_round_up"
+   echo "Total bitrate (bits): $total_bitrate"
+   echo "Audio bitrate (bits): $audio_bitrate"
+   echo "Video bitrate (bits): $video_bitrate"
+fi
+
+# If calculated video bitrate is still negative, throw error
+if [[ ! $video_bitrate -gt 0 ]]
+then
+   echo "ERROR: Video is too long to be compressed."
+   exit 1
 fi
 
 yt-dlp ${verbose} ${yt_dlp_params} --postprocessor-args "${postprocessor_args_str}" --output '%(title)s.%(ext)s' ${script_args[@]}
